---
title: AI4BioMed 2025 - Hands-on sessions installation instructions
format:
    html:
        embed-resources: true
        theme: cosmo
---

<style>
#title-block-header {
    margin-bottom: 3rem;
}
#title-block-header h1 {
    font-size: 2.5rem;
}


h2 {
    margin: 4rem 0 1rem 0;
}

h3 {
    margin: 2.5rem 0 1rem 0;
    font-size: 1.4rem;
}

</style>


## Install uv

This should already be done, but here are the installation instructions if necessary:

::: {.panel-tabset}

## Linux or MacOS

Open a terminal and run:

```sh
curl -LsSf https://astral.sh/uv/install.sh | sh
```

Then, open a new terminal and verify the installation:

```sh
uv --version
```

## Windows

Open a terminal (right click on the windows menu icon and select *Terminal*) then run:

```sh
powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"
```

After that, open a new terminal and verify the installation with:

```sh
uv --version
```

:::


## Download notebooks and data

Download and extract the following archive:

<TODO>

## Launch Jupyter lab

Open a new terminal at the root of the extracted archive and run:

```sh
uv run jupyter-lab
```

## If something fails...

If for some reason one of the previous steps fails, you still have the possibility to work on the notebooks in Google Colab (you will need an active internet connexion and a Google account).




